### ISSUE TITLE
Set up tablets

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#216]
https://dbcawa.atlassian.net/wiki/spaces/TG/pages/16974134/Turtle+Program+Collaborations

@florianm to update https://wastd.readthedocs.io/data_collection/data_collection_admin.html#admin-first-time-setup

**Comment by florian** [comment]
Please don't @ mention me. It subscribes me to this thread and I get a lot of emails.

**Comment by florianm** [comment]
Sorry mate, that was an undercaffeinated typo!
