### ISSUE TITLE
TFA conservation listings ETL: comments and dates

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#223]
> The other problem I have noticed is that there are comments in the listing table of the old database that aren’t in the new database.  Can the comments be copied across?

@MillyPiggott to include comments from TFA cons listings as TSC TaxonConservationListing.comments

> I’ve remembered an issue with the background Gazettal table headings in the old database.  I don’t remember if I told Florian about it before.  The front entry form headings were changed (by a previous person) but not the background table headings.  Table heading INTERIM should be “Reviewed by” and TRANSLOCATION should be “Review Outcome”.  I can update the table headings in the old database but I’m note sure how that may impact what has been programmed for TSC linking.  

@MillyPiggott to include the text from "reviewed by" and "review outcome" into comments.

> There’s also an issue with the review dates in TSC.  TSC is currently showing dates in the field for “Next review due” that are actually the “Last reviewed on” dates.  

@MillyPiggott to adjust TFA ETL - review due on vs last reviewed on.

**Comment by MillyPiggott** [comment]
Comments have been added to TSC and review dates amended.
TSC needs to be cleared and the data reloaded for the changes to take effect in TSC
