### ISSUE TITLE
Add area_occupied_method to PlantCount model, card template, API, admin

### ISSUE THREAD

**Issue by MillyPiggott** [dbca-wa/wastd#234]
Add area_occupied_method to Plant count model in TSC. We need this because area occupied can be different to the area surveyed, and is required for density calculations. Hence, we might need to know the method.

**Comment by florianm** [comment]
Could you get the plant count method value options from the TPFL manual?

**Comment by florianm** [comment]
* count_method already in model, admin, API
* added count_method, count_subject, count_accuracy to plantcount card (note: card doesn't contain all details to save screen space)
* tuned admins for ObservationGroups to prefetch > reduce SQL queries > admin much faster
