### ISSUE TITLE
ObsGroups created do not appear in GUI

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#249]
e.g. any TaxonAreaEncounter or CommunityAreaEncounter e.g.
https://tsc.dbca.wa.gov.au/occurrence/species/10437332/
"report xxx" e.g. Physical Sample
https://tsc.dbca.wa.gov.au/occurrence/10437332/physical-sample/report
(fill in fields) > save > nothing shows up in GUI at https://tsc.dbca.wa.gov.au/occurrence/species/10437332/ 

in admin (green pencil) https://tsc.dbca.wa.gov.au/admin/occurrence/taxonareaencounter/10437332/change/
physical sample is there...

seems like GUI caches, admin doesn't
on save - expire cache? what's the best caching strategy?

**Comment by ropable** [comment]
Pretty sure that this issue was due to aggressive caching, now resolved.
