### ISSUE TITLE
RESTful API should have a max records GET parameter

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#256]
## Problem

Current API has LimitOffset pagination. We need a way to restrict results to a given number of records. Would be neat to have this server side, could at a stretch implement in wastdr on the R side.

## Feature

Add a max_records parameter (name is up for discussion) to API to restrict number of (still paginated) records returned.

**Comment by ropable** [comment]
According to the [docs](https://www.django-rest-framework.org/api-guide/pagination/#configuration_1) we can configure the `LimitOffsetPagination` class with a `max_limit` setting, but that will limit the maximum allowable number of objects returned to the client at all times. Probably not what we want (unless we can just set that pagination class for particular model(s)).

**Comment by florianm** [comment]
Thanks, this reads as we should let the client decide when enough is enough, as in stop downloading the next page if the max records have been reached (or just exceeded).

The use case is to restrict downloading data to a manageable number of records, more than filtering precisely via max_records.

Closing this on the TSC end and implementing in `wastdr::wastd_GET(limit=NULL)`.
