### ISSUE TITLE
Admin won't load for WAStD Encounters with status > new

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#261]
## Reproducible example

* Step 1: Go to 
* Step 2: Do

**Comment by ropable** [comment]
Reproduced in dev by choosing "Proofread" for an Animal Encounter. Thereafter the server returns error "KeyError: "Key 'timestamp' not found in 'StateLogForm'. Choices are: id."

**Comment by ropable** [comment]
Error can be bypassed by commenting out all references to `CustomStateLogInline` in `wasd/observations/admin.py`

**Comment by ropable** [comment]
Error can be more-elegantly bypassed by altering `sortable_field_name = "timestamp"` to `sortable_field_name = "id"` in the `CustomStateLogInline` class in `shared/admin/py'. Has a field been removed from the `Encounter` base class at some point?

**Comment by ropable** [comment]
Going by the stack stack, the error seems to be some interation between django-fsm-log and grappelli. Unsure why. I suggest removing the `sortable_field_name` value from `CustomStateLogInline`.

**Comment by florianm** [comment]
Removing sortable_field_name is fine, IIRC I only added it after seeing a runtime error after a general third party library version upgrade bonanza.
