### ISSUE TITLE
Leaflet widget (e.g. in "report occurrence") link ‘valid GeoJSON Geometry’ contains advertising

### ISSUE THREAD

**Issue by brookerichards** [dbca-wa/wastd#310]
## Problem
When entering occurrences, the link ‘valid GeoJSON Geometry’ contains advertising. 

Remove link? Not required?

**Comment by florianm** [comment]
The offending link comes from code I have contributed to django-leaflet. 
I have raised the issue at https://github.com/makinacorpus/django-leaflet/issues/297

Having a direct link to an online GeoJSON validator is helpful for users to clean and validate their input.

**Comment by florianm** [comment]
TSC's leaflet map widget now links to geojson.io, which is free of ads as far as I can tell.
The map widget is used in every polygon or point form, both on the front end and in the data curation portal.
e.g. https://tsc.dbca.wa.gov.au/occurrence/report-species/
