### ISSUE TITLE
Entering Occurrences - Report Fire History - Date of Last Fire field

### ISSUE THREAD

**Issue by brookerichards** [dbca-wa/wastd#312]
## Problem
On our Threatened Priority Report Form the fields are broad. TSC database asks the user to narrow it down to a date. 

## Feature
Can we make the fields more broad?
Screen shot of the Threatened Priority Report Form fire fields below:
![image](https://user-images.githubusercontent.com/68680850/88876768-92321e80-d256-11ea-8dff-1b719b57e772.png)

**Comment by florianm** [comment]
The agreement was to choose the closest year, month, day (whichever possible).

**Comment by florianm** [comment]
Probably deserves a mention in the docs, as using a full date field (which we need, as some fire dates are known) for date info that is possibly of lower accuracy (to month or to year or to season) is not intuitive.
