### ISSUE TITLE
Entering Occurrences - Report Plant Count - Flowering descriptive note is incomplete

### ISSUE THREAD

**Issue by brookerichards** [dbca-wa/wastd#314]
## Problem
When entering occurrences under Report Plant Count the descriptive note under the 'flowering' field is incomplete.

**Comment by florianm** [comment]
Updated the help text.

**Comment by florianm** [comment]
Closed by https://github.com/dbca-wa/tsc/commit/90f17d2019ae31d9381c297b33770bba0648a43c
