### ISSUE TITLE
Entering Occurrences - Report Vegetation Classification - Descriptive notes issue

### ISSUE THREAD

**Issue by brookerichards** [dbca-wa/wastd#315]
## Problem
The descriptive notes for each classification level does not increase as the level increases. 

## Feature
Can we add in a note saying where to find the classification levels? Or turn this into a drop-down? From the Threatened Priority Report Form: ‘Structural formations should follow 2009 Australian Soil and Land Survey Field Handbook guidelines – refer to field manual for further information and structural formation table’.

**Comment by florianm** [comment]
Added fifth stratum, updated field labels to actual strata names, migrated db, added to model, admin, form, api. Template card coming in next patch.
