### ISSUE TITLE
QA/QC species

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#331]
## Accidental species records at incorrect locations

This would help to highlight species that are recorded at location where it is unlikely that the species would be recorded there for easier QA/QC.
## Feature

The idea is that each area, or whatever spatially based feature is best, has a list of commonly expected nesting species. When a QA/QC sweep is made by WAStD it checks this list against the observed species at that location and flags any that are unlikely to occur there. An example of this would be this Olive Ridley track seen at Port Hedland: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/167909/change/?_changelist_filters=area__id__exact%3D13%26species__exact%3Dlepidochelys-olivacea, could have happened but very unlikely.

A potential furthering of this idea is setting time spans at which certain species are expected to be seen, or certain activities of species. For instance I would think it would be unusual to have hawksbill nests hatching in late February at Port Hedland: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/159421/change/?_changelist_filters=area__id__exact%3D13%26species__exact%3Deretmochelys-imbricata. Talking to James about the aerial work he is looking at it seems you couldn't make an assumption about nesting times in Dampier Archipelago but it might work for other areas.

I also think the feature might be useful in pointing out unusual or interesting events occuring in areas where they might not be expected in the occasions where something is flagged but not an error.

**Comment by florianm** [comment]
TSC has a list of species <https://tsc.dbca.wa.gov.au/species/>
Search TSC species for Olive Ridley https://tsc.dbca.wa.gov.au/species/?vernacular_names=olive+ridley
Find Olive Ridley: https://tsc.dbca.wa.gov.au/species/25343/

Each TSC species has an EOO (extent of occurrence - currently badly approximated as spatial envelope of occurrence records) and an AOO (Area of Occupancy = sum of occurrence observations).
If the EOO were trustworthy and up to date (start with expert opinion from turtle team?), QA could retrieve EOO for each expected species (GN, FB, LH, HB, OR) and map all encounters outside of EOO envelope.
