### ISSUE TITLE
xls export date/time

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#332]
## Problem

When nest encounters is exported as an xls the 'Observed at' and 'Observed on' columns only contain errors and the spreadsheet has an error on first opening. 
![image](https://user-images.githubusercontent.com/11881636/92356443-b6680180-f118-11ea-8d19-eb9e9a2d024d.png)

## Reproducible example

Step 1: Select data to be exported and choose to export to xls. Here is a data selection URL I prepared earlier: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/?area__id__exact=17&when__day=25&when__month=11&when__year=2016
Step 2: Turn on headers (bug happens with that unselected too) and click Export. 
Step 3: Open the xls and look at the columns J and K. Column J says 'Unexpected data type <class 'django.contrib.gis.geos.point.Point'>', column K says 'can't subtract offset-naive and offset-aware datetimes'.
Step 4: Use the 'encounter ptr' column to extract the UTC date/time and calculate from there followed by filling out a Issue:Bug report on github.
Step 5: Try to attach xls, discover you can't then zip it and attach that.
[File with errors.zip](https://github.com/dbca-wa/wastd/files/5181458/File.with.errors.zip)

**Comment by florianm** [comment]
https://django-adminactions.readthedocs.io/en/latest/actions.html#export-as-csv
Include / exclude relevant columns
