### ISSUE TITLE
Nest encounter export to CSV structure

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#333]
## Problem

When exporting nest encounters to CSV it uses the same headers as exporting to xls (but worded differently) however only some of the columns are populated with the 'HTML representation' and 'Latex fragment' breaking the csv structure. 
[export with html and latex.zip](https://github.com/dbca-wa/wastd/files/5181579/export.with.html.and.latex.zip)

## Reproducible example

Step 1: Select you data to be exported, here is one I prepared earlier: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/?area__id__exact=17&when__day=25&when__month=11&when__year=2016
Step 2: Choose to export as csv.
Step 3: In the next screen select headers and at a minimum change the datetime format to not contain commas.
Step 4: Click export and open the file that was downloaded.
Step 5: Marvel at all the html and latex structure.

If I was to suggest a quick fix it would be to not allow the html and latex columns to be downloaded. They can be manually unselected and it works however this would often be forgotten and I suspect given they break the file serve no purpose anyway.

The comma issue is more difficult when thinking about the comments section, maybe an auto replace on export with something like a full stop if possible.

**Comment by florianm** [comment]
Those two columns are for display purposes - you could argue you'd want the CSV to create a map using the HTML as popup.
The CSV / XLS download is a pretty plain "out of the box" addon, maybe we can exclude those cols and default to quote and escape all content.

**Comment by RyanDou** [comment]
I guess this is thinking about the intended target audience with the CSV downloads. It's unlikely to be someone with the programming proficiency to take that CSV and utilise the HTML or Latex within to create anything. It's likely someone who wants a quick look at the data to answer some random one off question that they have about something and don't have the proficiency to utilise the R script to achieve that end.

**Comment by florianm** [comment]
Closing for now. Users can select columns to export in the export screen.
