### ISSUE TITLE
Commas in WAStD breaking csv export

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#334]
## Problem

CSV export doesn't output as hoped due to commas in WAStD and default datetime format.
## Reproducible example

Step 1: Select data to export and select to export as a csv. Here is a selection used to test: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/?area__id__exact=17&when__day=25&when__month=11&when__year=2016
Step 2: Note that the default datetime format include 2 commas with interfere with a csv's formatting. Remove the commas to, select to show headers and click export to continue.
Step 3: Notice that the data extends either one or two fields past the headers depending on the fields entering in ODK and if any comments contain commas. In the example export all observations contain '(F )fresh, made last night', one contains 'nest, hatched' and one contains a comma in the comments.

My advice for the datetime is change the defaults to something like 'd/m/Y H:i' as default datetime, 'd/m/Y' as default date and 'H:i' as default time. Though I do understand that ISO 8601 date format is 'Y-m-d'.
Not sure how to handle all the other commas, maybe an auto change on export to make them all full stops?

**Comment by florianm** [comment]
![image](https://user-images.githubusercontent.com/762815/92375229-6e0a0d00-f133-11ea-8f0a-465c7714dc9e.png)
- [ ] These working export settings should be enabled by default
- [ ] Add above settings to docs

**Comment by florianm** [comment]
https://django-adminactions.readthedocs.io/en/latest/actions.html#export-as-csv

**Comment by florianm** [comment]
There doesn't seem to be a way to set defaults for the [export to CSV options](https://django-adminactions.readthedocs.io/en/latest/api.html#export-as-csv).
