### ISSUE TITLE
New line in comments causing entry to cover 2 lines in csv export

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#340]
## Problem

When exporting via CSV records with a new line manually added in the comments field causes the observation to be split over 2 lines based on where the new line was added.
## Reproducible example

If you export these observations via CSV you will get 19 lines of observations instead of the expected 16: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/?area__id__exact=17&species__exact=natator-depressus&status__exact=proofread
The only commonality I can find between the observations split over 2 lines is that there was the automated name change comment and then a new line was made where a second comment was added so I presume this is what is causing the issue. For example these 2 observations go over 2 lines:
https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/9868/change/
https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/5743/change/
However these with no added line breaks work fine:
https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/11499/change/?_changelist_filters=area__id__exact%3D17%26species__exact%3Dnatator-depressus%26status__exact%3Dproofread
https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/3318/change/?_changelist_filters=area__id__exact%3D17%26species__exact%3Dnatator-depressus%26status__exact%3Dproofread

**Comment by florianm** [comment]
The CSV export requires an "escapechar" to be set:
![image](https://user-images.githubusercontent.com/762815/93409376-5d8f2a80-f8c9-11ea-811b-ec40efa53589.png)

This will "escape" any control characters like a newline or a comma in text fields.

The docs should be clearer on this.

**Comment by RyanDou** [comment]
I tried using the escapechar and it still caused the extra columns. It also creates the extra rows too. These are the settings used: 
![image](https://user-images.githubusercontent.com/11881636/93412058-02603680-f8cf-11ea-97f9-42af15addd43.png)
I don't think this is the same issue as #339 is it? One creates extra columns and the other creates extra rows

**Comment by RyanDou** [comment]
Oh, and here is the file created with above
[turtle_nest_encounters (31).zip](https://github.com/dbca-wa/wastd/files/5235861/turtle_nest_encounters.31.zip)

**Comment by florianm** [comment]
Did you try quotechar `"`?

**Comment by RyanDou** [comment]
That worked, so the documentation will need to specify both quotechar and escapechar, though hopefully defaults can also be set.
