### ISSUE TITLE
Migrate django-fsm to viewflow

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#411]
## Problem

django-fsm is at end of life after 10 amazing years: https://github.com/viewflow/django-fsm/issues/256#issuecomment-961667548

## Feature

Now: upgrade django-fsm to v2.8.0 https://github.com/viewflow/django-fsm/tree/2.8.0
Near future: Reduce tech debt - migrate to use https://docs-next.viewflow.io/overview/index.html

**Comment by anandrajB** [comment]
viewflow.fsm has major bug 
the state transitions aren't changing

like django-fsm we have fsmfield
does viewflow has that ?

**Comment by florianm** [comment]
Sorry, I don't know about that, I'm not the maintainer of viewflow. This issue is a note to myself to upgrade my own project.
