### ISSUE TITLE
Import Cetacean strandings

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#74]
## Discuss data mapping
can be done in 2h with cet strandings data custodian

clarify species in cet db not in wastd:

['',
 'Balaenoptera musculus ? brevicauda',
 'Tasmacetus shepherdi ?',
 'Mesoplodon bowdoini',
 'Mesoplodon mirus',
 'Balaenopter musculus brevicauda',
 'Balaenoptera ? musculus ? brevicauda',
 'Mesoplodon grayi',
 'Physeter macrocephalus ',
 'Orcaella heinsohni x ?',
 'Tursiops truncatus    ',
 'Tursiops truncatus ',
 'Sousa chinensis',
 'Kogia simus',
 'Stenella  sp ? (coeruleoalba)',
 'Caperea marginata',
 'Balaenopters cf. B. omurai',
 'Mesoplodon hectori',
 'Berardius arnuxii',
 'Mesoplodon grayi (?)',
 'Tasmacetus shepherdi',
 'Mesoplodon sp']

* observed by, recorded by: not in cet db
* cause of death mapping
* health mapping

**Comment by alexrchapman** [comment]
AFD (or via the ALA) is the best place to source the current names/spellings for these taxa: https://biodiversity.org.au/afd/home

**Comment by florianm** [comment]
Ready for production.

Good: location, date, species, cause of death.

Requires curation of unstructured comments: health, measurements
